---

- name: create block device list
  set_fact:
    devices: "{{ ansible_devices| reject('search', '^(sda|sr0)') | list }}"

- name: Create a xfs filesystem on /dev/xxx
  filesystem:
    fstype: xfs
    dev: "/dev/{{ item }}"
    opts: "-f -d agcount=32"
  with_items:
    - "{{ devices }}"

- name: create directory to mount to
  file:
    path: /data
    state: directory
    mode: 0755
    recurse: yes

- name: create directory to mount to
  file:
    path: /data/k8s{{ item.0 }}
    state: directory
    mode: 0755
    recurse: yes
  with_indexed_items:
    - "{{ devices }}"

- name: mount block to data dir
  mount:
    path: /data/k8s{{ item.0 }}
    src: /dev/{{ item.1 }}
    fstype: xfs
    state: mounted
    opts: noatime
  with_indexed_items:
    - "{{ devices }}"

- name: Setting noop scheduler
  shell: echo noop > /sys/block/"{{ item }}"/queue/scheduler
  with_items:
    - "{{ devices }}"
  
- name: blockdev
  shell: blockdev --getra /dev/"{{ item }}"
  with_items:
    - "{{ devices }}"
  register: result

- name: Modifying read-ahead per block devices
  lineinfile:
    path: /etc/udev/rules.d/20-"{{ item }}".rules
    line: 'ACTION=="add|change", KERNEL=="{{ item }}", ATTR{queue/scheduler}="noop", ATTR{bdi/read_ahead_kb}="32"'
    state: present
    create: yes
  when: result.stdout_lines != 64
  with_items:
    - "{{ devices }}"
  register: ra